name: Build and Publish Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test      
      - name: Set SQLite DB location
        env:
          SQLITE_DB_LOCATION: /tmp/todo.db

